import type { Metadata } from "next";
import "./globals.css";
import { publicSans, timmana } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Fintrack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${publicSans.className} ${timmana.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
